
INSERT INTO profession (acronimo,name) values ('abgdo', 'abogado');
INSERT INTO profession (acronimo,name) values ('adm', 'administrador');
INSERT INTO profession (acronimo,name) values ('alcde', 'alcalde');
INSERT INTO profession (acronimo,name) values ('almte', 'almirante');
INSERT INTO profession (acronimo,name) values ('anl', 'analista');
INSERT INTO profession (acronimo,name) values ('arq', 'arquitecto');
INSERT INTO profession (acronimo,name) values ('bach', 'bachiller');
INSERT INTO profession (acronimo,name) values ('brig', 'brigadier');
INSERT INTO profession (acronimo,name) values ('cap', 'capitán');
INSERT INTO profession (acronimo,name) values ('cnl', 'cardenal');
INSERT INTO profession (acronimo,name) values ('clg', 'clérigo');
INSERT INTO profession (acronimo,name) values ('comte', 'comandante');
INSERT INTO profession (acronimo,name) values ('coord', 'coordinador');
INSERT INTO profession (acronimo,name) values ('cP', 'contador público');
INSERT INTO profession (acronimo,name) values ('cnel', 'coronel');
INSERT INTO profession (acronimo,name) values ('cdor', 'contador');
INSERT INTO profession (acronimo,name) values ('dir', 'director');
INSERT INTO profession (acronimo,name) values ('dira', 'directora');
INSERT INTO profession (acronimo,name) values ('dr', 'doctor');
INSERT INTO profession (acronimo,name) values ('econ', 'economista');
INSERT INTO profession (acronimo,name) values ('gte', 'gerente');
INSERT INTO profession (acronimo,name) values ('gdor', 'gobernador');
INSERT INTO profession (acronimo,name) values ('gdora', 'gobernadora');
INSERT INTO profession (acronimo,name) values ('gral', 'general');
INSERT INTO profession (acronimo,name) values ('ing', 'ingeniero');
INSERT INTO profession (acronimo,name) values ('jz', 'juez');
INSERT INTO profession (acronimo,name) values ('lcdo', 'licenciado');
INSERT INTO profession (acronimo,name) values ('lcda', 'licenciada');
INSERT INTO profession (acronimo,name) values ('may. Brig', 'mayor');
INSERT INTO profession (acronimo,name) values ('not', 'notario');
INSERT INTO profession (acronimo,name) values ('nut', 'nutrisionista');
INSERT INTO profession (acronimo,name) values ('ob', 'obispo');
INSERT INTO profession (acronimo,name) values ('odont', 'odontologo');
INSERT INTO profession (acronimo,name) values ('pdte', 'presidente');
INSERT INTO profession (acronimo,name) values ('pdta', 'presidenta');
INSERT INTO profession (acronimo,name) values ('PM', 'policia militar');
INSERT INTO profession (acronimo,name) values ('prof', 'profesor');
INSERT INTO profession (acronimo,name) values ('profa', 'profesora');
INSERT INTO profession (acronimo,name) values ('psic', 'psicólogo');
INSERT INTO profession (acronimo,name) values ('psiq', 'psiquiatra');
INSERT INTO profession (acronimo,name) values ('quim', 'quimico');
INSERT INTO profession (acronimo,name) values ('qF', 'quimico farmaceutico');
INSERT INTO profession (acronimo,name) values ('soc', 'sociólogo');
INSERT INTO profession (acronimo,name) values ('superv', 'supervisor');
INSERT INTO profession (acronimo,name) values ('tle', 'teniente');
INSERT INTO profession (acronimo,name) values ('tnco', 'tecnico');
INSERT INTO profession (acronimo,name) values ('TM', 'tecnico medico');
INSERT INTO profession (acronimo,name) values ('tnlgo', 'tecnologo');
INSERT INTO profession (acronimo,name) values ('ts', 'trabajador social');
INSERT INTO profession (acronimo,name) values ('vet', 'veterinario');